In [1]:
import pandas as pd

df=pd.read_csv('swiggy.csv')

In [2]:
df.head()

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8680 entries, 0 to 8679
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             8680 non-null   int64
 1   Area           8680 non-null   str
 2   City           8680 non-null   str
 3   Restaurant     8680 non-null   str
 4   Price          8680 non-null   float64
 5   Avg ratings    8680 non-null   float64
 6   Total ratings  8680 non-null   int64
 7   Food type      8680 non-null   str
 8   Address        8680 non-null   str
 9   Delivery time  8680 non-null   int64
dtypes: float64(2), int64(3), str(5)
memory usage: 678.3 KB

In [4]:
df.describe()

                  ID        Price  Avg ratings  Total ratings  Delivery time
count    8680.000000  8680.000000  8680.000000    8680.000000    8680.000000
mean   244812.071429   348.444470     3.655104     156.634793      53.967051
std    158671.617188   230.940074     0.647629     391.448014      14.292335
min       211.000000     0.000000     2.000000      20.000000      20.000000
25%     72664.000000   200.000000     2.900000      50.000000      44.000000
50%    283442.000000   300.000000     3.900000      80.000000      53.000000
75%    393425.250000   400.000000     4.200000     100.000000      64.000000
max    466928.000000  2500.000000     5.000000   10000.000000     109.000000

In [5]:
df.describe(include='all')

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
count,8680.000000,8680,8680,8680,8680.000000,8680.000000,8680.000000,8680,8680,8680.000000
unique,NaN,833,9,7865,NaN,NaN,NaN,3734,2339,NaN
top,NaN,Rohini,Kolkata,La Pino'Z Pizza,NaN,NaN,NaN,Indian,Rohini,NaN
freq,NaN,257,1346,13,NaN,NaN,NaN,389,229,NaN
mean,244812.071429,NaN,NaN,NaN,348.444470,3.655104,156.634793,NaN,NaN,53.967051
std,158671.617188,NaN,NaN,NaN,230.940074,0.647629,391.448014,NaN,NaN,14.292335
min,211.000000,NaN,NaN,NaN,0.000000,2.000000,20.000000,NaN,NaN,20.000000
25%,72664.000000,NaN,NaN,NaN,200.000000,2.900000,50.000000,NaN,NaN,44.000000
50%,283442.000000,NaN,NaN,NaN,300.000000,3.900000,80.000000,NaN,NaN,53.000000
75%,393425.250000,NaN,NaN,NaN,400.000000,4.200000,100.000000,NaN,NaN,64.000000
max,466928.000000,NaN,NaN,NaN,2500.000000,5.000000,10000.000000,NaN,NaN,109.000000

In [6]:
df.isnull().sum()

ID               0
Area             0
City             0
Restaurant       0
Price            0
Avg ratings      0
Total ratings    0
Food type        0
Address          0
Delivery time    0
dtype: int64

In [7]:
df['Avg ratings']=df['Avg ratings'].round(1)

In [8]:
df.head(15)

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63
5,254,Indiranagar,Bangalore,Treat,800.0,4.5,100,"Mughlai,North Indian",100 Feet Road,56
6,258,Indiranagar,Bangalore,Chinita Real Mexican Food,1000.0,4.5,500,"Mexican,Beverages,Salads",Double Road,53
7,263,Koramangala,Bangalore,Cupcake Noggins - Cakespastries And Desserts,150.0,4.3,100,"Desserts,British,Bakery,Pizzas,Snacks",4Th Block,57
8,267,Domlur,Bangalore,Tea Brew,350.0,4.1,100,"American,Italian,Beverages,Continental,Chinese...",Double Road,57
9,308,Koramangala,Bangalore,Bangaliana,300.0,4.0,500,Bengali,7Th Block,57
10,435,Koramangala,Bangalore,Bamey'S Restro Cafe,400.0,4.4,100,"Chinese,Thai,Nepalese",5Th Block,56
11,446,Cooke Town,Bangalore,Altaf'S Chillies Restaurants,250.0,4.3,500,"North Indian,Chinese",Cooke Town,55
12,453,Pulikeshi Nagar,Bangalore,Chichabas Taj,532.0,4.2,100,"Mughlai,North Indian,Biryani",Mm Road,54
13,464,Sivanchetti Gardens,Bangalore,Urban Solace,500.0,2.9,80,"American,Continental",Ulsoor Lake,48
14,504,Kodihalli,Bangalore,Kaati Zone Rolls & Wraps,150.0,4.3,100,"Fast Food,Beverages,Bengali,Biryani,Indian,Nor...",Domlur Layout,59

In [9]:
df['Price']=df['Price'].round(1)

In [10]:
df.head()

,ID,Area,City,Restaurant,Price,Avg ratings,Total ratings,Food type,Address,Delivery time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

In [11]:
df.columns

Index(['ID', 'Area', 'City', 'Restaurant', 'Price', 'Avg ratings',
       'Total ratings', 'Food type', 'Address', 'Delivery time'],
      dtype='str')

In [12]:
df.columns=df.columns.str.replace(' ','_')

In [13]:
df.columns

Index(['ID', 'Area', 'City', 'Restaurant', 'Price', 'Avg_ratings',
       'Total_ratings', 'Food_type', 'Address', 'Delivery_time'],
      dtype='str')

In [14]:
df.columns=df.columns.str.title()

In [15]:
df.columns

Index(['Id', 'Area', 'City', 'Restaurant', 'Price', 'Avg_Ratings',
       'Total_Ratings', 'Food_Type', 'Address', 'Delivery_Time'],
      dtype='str')

In [16]:
df.head()

,Id,Area,City,Restaurant,Price,Avg_Ratings,Total_Ratings,Food_Type,Address,Delivery_Time
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63

In [17]:
def price_map(x):
    if x<200: 
        return "Budget"
    elif x>=200 and x <400:
        return "Medium-Range"
    else :
        return "Costly"

df['Price_Category']=df['Price'].apply(price_map)

In [18]:
df[['Price','Price_Category']].head(8)

    Price Price_Category
0   300.0   Medium-Range
1   300.0   Medium-Range
2   650.0         Costly
3   250.0   Medium-Range
4   350.0   Medium-Range
5   800.0         Costly
6  1000.0         Costly
7   150.0         Budget

In [19]:
df['Price_Category']=df['Price_Category'].replace('Medium-Range','Mid Value')

In [20]:
df.head()

,Id,Area,City,Restaurant,Price,Avg_Ratings,Total_Ratings,Food_Type,Address,Delivery_Time,Price_Category
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59,Mid Value
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56,Mid Value
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50,Costly
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57,Mid Value
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63,Mid Value

In [21]:
df['Delivery_Time'].value_counts()

Delivery_Time
52     274
47     265
49     263
46     252
44     246
      ...
21       1
109      1
100      1
20       1
22       1
Name: count, Length: 81, dtype: int64

In [22]:
df['Delivery_Time'].describe()

count    8680.000000
mean       53.967051
std        14.292335
min        20.000000
25%        44.000000
50%        53.000000
75%        64.000000
max       109.000000
Name: Delivery_Time, dtype: float64

In [23]:
def del_stats(x):
    if x<45:
        return "Fast"
    elif x>=45 and x<80 :
        return "Moderate"
    else: 
        return "Slow"

df['Delivery_Status']=df['Delivery_Time'].apply(del_stats)

In [24]:
df[['Delivery_Time','Delivery_Status']].head()

   Delivery_Time Delivery_Status
0             59        Moderate
1             56        Moderate
2             50        Moderate
3             57        Moderate
4             63        Moderate

In [25]:
df['Avg_Ratings'].unique()

array([4.4, 4.1, 3.9, 4. , 4.5, 4.3, 4.2, 2.9, 3.8, 4.6, 3.7, 3.2, 2.2,
       3.6, 4.7, 3.5, 3. , 3.3, 3.4, 2.8, 4.8, 4.9, 2.6, 2.7, 3.1, 2.5,
       2.3, 5. , 2. , 2.4])

In [26]:
def avg_rate(x):
    if x<=3:
        return "Low Rated"
    elif x>3 and x<=4:
        return "Avg Rated"
    else:
        return "High Rated"

df['Rating_Status']=df['Avg_Ratings'].apply(avg_rate)

In [27]:
df.head()

,Id,Area,City,Restaurant,Price,Avg_Ratings,Total_Ratings,Food_Type,Address,Delivery_Time,Price_Category,Delivery_Status,Rating_Status
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59,Mid Value,Moderate,High Rated
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56,Mid Value,Moderate,High Rated
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50,Costly,Moderate,High Rated
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57,Mid Value,Moderate,Avg Rated
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63,Mid Value,Moderate,Avg Rated

In [28]:
df['Primary_Cuisine']=df['Food_Type'].str.split(',').str[0].str.strip()

In [29]:
df.head()

,Id,Area,City,Restaurant,Price,Avg_Ratings,Total_Ratings,Food_Type,Address,Delivery_Time,Price_Category,Delivery_Status,Rating_Status,Primary_Cuisine
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59,Mid Value,Moderate,High Rated,Biryani
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56,Mid Value,Moderate,High Rated,Mughlai
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50,Costly,Moderate,High Rated,Chinese
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57,Mid Value,Moderate,Avg Rated,North Indian
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63,Mid Value,Moderate,Avg Rated,Rajasthani

In [30]:
df['Number_Of_Cuisines']=df['Food_Type'].str.split(',').apply(len)

In [31]:
df.head()

,Id,Area,City,Restaurant,Price,Avg_Ratings,Total_Ratings,Food_Type,Address,Delivery_Time,Price_Category,Delivery_Status,Rating_Status,Primary_Cuisine,Number_Of_Cuisines
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59,Mid Value,Moderate,High Rated,Biryani,4
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56,Mid Value,Moderate,High Rated,Mughlai,2
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50,Costly,Moderate,High Rated,Chinese,1
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57,Mid Value,Moderate,Avg Rated,North Indian,4
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63,Mid Value,Moderate,Avg Rated,Rajasthani,8

In [32]:
df['City'].value_counts()

City
Kolkata      1346
Mumbai       1277
Chennai      1106
Pune         1090
Hyderabad    1075
Bangalore     946
Ahmedabad     717
Delhi         611
Surat         512
Name: count, dtype: int64

In [33]:
df['Total_Ratings'].unique()

array([  100,   500,    50,    80,  1000,  5000,    20, 10000])

In [34]:
import numpy as np

df['Popularity_Score']=(df['Avg_Ratings'] * np.log1p(df['Total_Ratings'])).round(3)

In [35]:
df.head()

,Id,Area,City,Restaurant,Price,Avg_Ratings,Total_Ratings,Food_Type,Address,Delivery_Time,Price_Category,Delivery_Status,Rating_Status,Primary_Cuisine,Number_Of_Cuisines,Popularity_Score
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59,Mid Value,Moderate,High Rated,Biryani,4,20.307
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56,Mid Value,Moderate,High Rated,Mughlai,2,18.922
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50,Costly,Moderate,High Rated,Chinese,1,20.307
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57,Mid Value,Moderate,Avg Rated,North Indian,4,24.245
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63,Mid Value,Moderate,Avg Rated,Rajasthani,8,15.727

In [36]:
df['Popularity_Score'].unique()

array([20.307, 18.922, 24.245, 15.727, 20.768, 27.975, 19.845, 24.866,
       26.731, 19.384, 12.744, 29.017, 17.537, 25.488, 34.921, 18.46 ,
       26.11 , 16.12 , 27.353, 27.635, 29.708, 28.326, 21.23 , 16.907,
       12.787, 15.334, 17.999, 31.089, 14.548, 37.763, 23.001, 26.944,
       26.253, 35.921, 30.399,  9.742,  6.698, 16.614, 12.483, 29.218,
       32.471, 36.625, 23.623, 17.693, 13.7  , 17.3  , 11.874, 12.178,
       17.076, 21.691, 25.562, 11.569, 16.514, 10.656, 13.091, 11.265,
       13.396, 14.941, 10.96 , 22.38 , 18.48 , 33.218,  9.134, 15.23 ,
       13.761, 12.582, 14.155, 34.07 , 18.086, 13.368, 23.49 , 36.842,
       28.596, 16.153,  8.525, 10.351, 14.614, 14.005, 11.402, 14.918,
       14.309, 22.153, 32.366, 15.691, 14.768,  7.916, 12.975, 24.181,
        8.22 , 10.047, 18.873, 13.845, 10.616, 12.189, 11.795,  9.438,
       14.307, 21.136, 13.384, 35.773,  8.829,  7.611, 31.78 ,  7.002,
       24.872, 15.223,  6.089,  8.65 , 19.659, 38.328, 21.758,  7.307,
       29.84 ])

In [37]:
df['Popularity_Score'].describe()

count    8680.000000
mean       16.191183
std         5.000317
min         6.089000
25%        12.744000
50%        13.091000
75%        18.922000
max        38.328000
Name: Popularity_Score, dtype: float64

In [38]:
def pop_stat(score):
    if score <10:
        return "Less Popular"
    elif score >=10 and score <25:
        return "Average Popular"
    else:
        return "More Popular"

df['Popularity_Status']=df['Popularity_Score'].apply(pop_stat)

In [39]:
df.head()

,Id,Area,City,Restaurant,Price,Avg_Ratings,Total_Ratings,Food_Type,Address,Delivery_Time,Price_Category,Delivery_Status,Rating_Status,Primary_Cuisine,Number_Of_Cuisines,Popularity_Score,Popularity_Status
0,211,Koramangala,Bangalore,Tandoor Hut,300.0,4.4,100,"Biryani,Chinese,North Indian,South Indian",5Th Block,59,Mid Value,Moderate,High Rated,Biryani,4,20.307,Average Popular
1,221,Koramangala,Bangalore,Tunday Kababi,300.0,4.1,100,"Mughlai,Lucknowi",5Th Block,56,Mid Value,Moderate,High Rated,Mughlai,2,18.922,Average Popular
2,246,Jogupalya,Bangalore,Kim Lee,650.0,4.4,100,Chinese,Double Road,50,Costly,Moderate,High Rated,Chinese,1,20.307,Average Popular
3,248,Indiranagar,Bangalore,New Punjabi Hotel,250.0,3.9,500,"North Indian,Punjabi,Tandoor,Chinese",80 Feet Road,57,Mid Value,Moderate,Avg Rated,North Indian,4,24.245,Average Popular
4,249,Indiranagar,Bangalore,Nh8,350.0,4.0,50,"Rajasthani,Gujarati,North Indian,Snacks,Desser...",80 Feet Road,63,Mid Value,Moderate,Avg Rated,Rajasthani,8,15.727,Average Popular

In [40]:
df.to_csv('swiggy_final.csv',index=False)

In [45]:
import sqlalchemy,psycopg2

In [46]:
from sqlalchemy import create_engine

In [49]:
username='postgres'
password='Shivam26'
host='localhost'
port='5432'
database='swiggy_data'

engine=create_engine(f'postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}')

table_name='swiggy'

df.to_sql(table_name,engine,if_exists="replace",index=False)

print(f"Data has been successfully added to database :{database} into table {table_name}")

Data has been successfully added to database :swiggy_data into table swiggy